using System;
using System.Collections.Generic;
using AsiActionEngine.RunTime;
using UnityEngine;
#if YooAsset
using YooAsset;
#endif
#if Addressables
#endif

namespace AsiTimeLine.RunTime
{
    public class ActionEnginLoadData
    {
        #region Instance
        private static ActionEnginLoadData _instance;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void ResetStatics()
        {
            // Enter Play Mode may run with Domain Reload disabled. Never carry a
            // previously deserialized UnitWarp across Play sessions after its
            // Addressable binary has been regenerated by the Action Editor.
            _instance = null;
        }

        public static ActionEnginLoadData Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ActionEnginLoadData();
                }
                return _instance;
            }
        }
        #endregion


        private string Suffixes => ActionEngineRuntimePath.Suffixes;
        public Dictionary<string, object> AllLoadData => m_AllLoadData;

        private Dictionary<string, object> m_AllLoadData = new();
        private Dictionary<string, List<Action<object>>> m_WaitAsyncLoad = new();
        private HashSet<string> m_PreloadWarmUp = new();
        private bool m_Init = false;
        // private ActionEngineManager ActionEngineManager { get; set; }
        public void Init()
        {
            if (m_Init) return;
            m_Init = true;
            //EngineDebug.LogError("初始化");
            // ActionEngineManager = actionEngineManager;
            m_AllLoadData.Clear();
            m_WaitAsyncLoad.Clear();
            m_PreloadWarmUp.Clear();
            ActionEngineRuntimePath.Instance.init();
        }

        public void LoadInfo(EInfoType _type, Action<object> _action, int _id, ERuntimeDataChannel _channel = ERuntimeDataChannel.Local)
        {
            Init();
            if (HasChannelSpecificData(_type))
            {
                ActionEngineManager manager = ActionEngineManager.Instance;
                if (manager != null)
                {
                    _channel = manager.ResolveRuntimeChannel(_channel);
                }
            }
            else
            {
                _channel = ERuntimeDataChannel.Local;
            }
            string _baseName = GetDataName(_type, _id);
            // 通道后缀参与缓存 Key 与文件名，避免不同通道同 id 互相命中缓存
            string _name = _baseName + RuntimeDataChannel.GetChannelSuffix(_channel);

            if (m_AllLoadData.TryGetValue(_name, out object _value))
            {
                //已加载过此键值，直接返回参数
                _action(_value);
            }
            else
            {
                if (m_WaitAsyncLoad.ContainsKey(_name))
                {
                    //已存在此键值，但是异步还未完成加载，在此等候异步完成一起回调
                    m_WaitAsyncLoad[_name].Add(_action);
                }
                else
                {
                    //第一次加载此Key值参数，创建list储存起来
                    List<Action<object>> _waitAsync = new();
                    _waitAsync.Add(_action);
                    m_WaitAsyncLoad.Add(_name, _waitAsync);
                    string _path = GetDataPath(_type, _name);
#if UNITY_EDITOR && !Addressables
                    // Remote 数据缺失时允许回退本地数据便于调试；Server 必须保持纯逻辑数据边界，禁止回退。
                    // 真机 StreamingAssets 无法可靠 File.Exists，依赖保存时三通道文件均已生成。
                    if (_channel != ERuntimeDataChannel.Local && !System.IO.File.Exists(_path))
                    {
                        if (_channel == ERuntimeDataChannel.Server)
                        {
                            EngineDebug.LogError($"服务端数据缺失，禁止回退本地完整数据: [<color=#ff0000>{_path}</color>]");
                        }
                        else
                        {
                            EngineDebug.LogWarning($"通道[<color=#ffcc00>{_channel}</color>]数据缺失，回退本地加载: [<color=#ffcc00>{_path}</color>]");
                            _path = GetDataPath(_type, _baseName);
                        }
                    }
#endif

                    // string _saveName = _name;
                    Action<object> _callback = (_obj) =>
                    {
                        string _saveName = _name;
                        object loadedObject = _obj;
                        try
                        {
                            if (loadedObject is IProperty property)
                                property.Init();
                        }
                        catch (Exception exception)
                        {
                            EngineDebug.LogError($"数据初始化失败 key=[{_saveName}]: {exception}");
                            loadedObject = null;
                        }

                        if (!m_WaitAsyncLoad.TryGetValue(
                                _saveName, out List<Action<object>> waiters))
                        {
                            EngineDebug.LogError($"异步数据等待队列丢失 key=[{_saveName}]");
                            return;
                        }
                        m_WaitAsyncLoad.Remove(_saveName);

                        if (loadedObject != null &&
                            !m_AllLoadData.TryAdd(_saveName, loadedObject))
                        {
                            EngineDebug.LogError($"重复添加Key: [<color=#ffcc00>{_saveName}</color>]");
                        }

                        for (int waiterIndex = 0; waiterIndex < waiters.Count; waiterIndex++)
                        {
                            try
                            {
                                waiters[waiterIndex]?.Invoke(loadedObject);
                            }
                            catch (Exception exception)
                            {
                                EngineDebug.LogError(
                                    $"异步数据完成回调失败 key=[{_saveName}] index=[{waiterIndex}]: {exception}");
                            }
                        }

                        if (_channel != ERuntimeDataChannel.Server && loadedObject is ActionStateInfo _info)
                        {
                            EngineDebug.LogWarning($"加载的动作组[<color=#ffcc00>{_info.ActionGroupID}</color>]");
                            PreloadParticleEffects(_info);
                        }
                    };

                    EngineResourcesManager.Instance.AsyncLoadBinary(_path, _callback);
                }
            }
        }

        private static bool HasChannelSpecificData(EInfoType _type)
        {
            return _type == EInfoType.UnitAction || _type == EInfoType.Skill;
        }

        // 装载动作数据完成后，按编辑器保存时收集的 mCollectWarmUp 列表预热对象池，
        // 避免运行时首次播放时阻塞在 Addressables 异步加载上。
        private void PreloadParticleEffects(ActionStateInfo _info)
        {
            if (_info?.mCollectWarmUp == null || _info.mCollectWarmUp.Count == 0) return;

            int _added = 0;
            foreach (string _path in _info.mCollectWarmUp)
            {
                if (string.IsNullOrEmpty(_path)) continue;
                if (!m_PreloadWarmUp.Add(_path)) continue;
                PrewarmParticle(_path);
                _added++;
            }

            if (_added > 0)
            {
                EngineDebug.Log($"[ActionEnginLoadData] 动作组[<color=#ffcc00>{_info.ActionGroupID}</color>] 新增预热特效 path 数=[<color=#ffcc00>{_added}</color>] 累计预热=[<color=#ffcc00>{m_PreloadWarmUp.Count}</color>]");
            }
        }

        // 预热单个特效 path：建立对象池 + 异步加载 prefab，回调内立即归还，
        // 让池里留下一个空闲实例（首次实际播放时直接命中池）。
        private void PrewarmParticle(string _path)
        {
            EngineDebug.Log($"[ActionEnginLoadData] 预热特效 path=[<color=#ffcc00>{_path}</color>]");
            EngineResourcesManager.Instance.CreactObjToComponent<ActionEngine_Effects>(
                _path,
                _comp =>
                {
                    if (_comp != null)
                    {
                        EngineDebug.Log($"[ActionEnginLoadData] 预热完成 path=[<color=#ffcc00>{_path}</color>] type=[{_comp.GetType().Name}]");
                        EngineResourcesManager.Instance.RemoveComponent(_path, _comp);
                    }
                    else
                    {
                        EngineDebug.LogWarning($"[ActionEnginLoadData] 预热失败 path=[<color=#ff0000>{_path}</color>] 返回 null");
                    }
                }, objPoolParent: (int)EObjPoolParent.Effects);
        }

        private string GetDataName(EInfoType _type, int _id)
        {
            if (_type == EInfoType.InputModule)
            {
                return "data_ae_input_module";
                //return ActionEngineRuntimePath.DataName_Input + _id;
            }
            else if (_type == EInfoType.AssetData)
            {
                return "data_ae_asset_key";
                //return ActionEngineRuntimePath.DataName_Asset + _id;
            }
            else if (_type == EInfoType.UnitWarp)
            {
                return ActionEngineRuntimePath.DataName_Unit + _id;
            }
            else if (_type == EInfoType.UnitAction)
            {
                return ActionEngineRuntimePath.DataName_Action + _id;
            }
            else if (_type == EInfoType.CameraWarp)
            {
                return ActionEngineRuntimePath.DataName_Cam + _id;
            }
            else if (_type == EInfoType.GValue)
            {
                return ActionEngineRuntimePath.DataName_Gvalue + _id;
            }
            else if (_type == EInfoType.Equation)
            {
                return ActionEngineRuntimePath.DataName_Equation + _id;
            }
            else if (_type == EInfoType.PropWarp)
            {
                return ActionEngineRuntimePath.DataName_Module + _id;
            }
            else if (_type == EInfoType.Skill)
            {
                return ActionEngineRuntimePath.DataName_Skill + _id;
            }
#if UNITY_EDITOR
            EngineDebug.LogError("数据类型错误：" + _type);
#endif
            return "Error";
        }
        private string GetDataPath(EInfoType _type, string _name)
        {
#if Addressables
            return _name;
#endif
            string _path = "";
            ActionEngineRuntimePath aerp = ActionEngineRuntimePath.Instance;
            switch (_type)
            {
                case EInfoType.UnitAction: _path = aerp.ActionLoadPath(_name) + Suffixes; break;
                case EInfoType.InputModule: _path = aerp.InputModuleLoadPath() + Suffixes; break;
                case EInfoType.CameraWarp: _path = aerp.CameraLoadPath(_name) + Suffixes; break;
                case EInfoType.AssetData: _path = aerp.AssetDataLoadPath(_name) + Suffixes; break;
                case EInfoType.UnitWarp: _path = aerp.UnitWarpLoadPath(_name) + Suffixes; break;
                case EInfoType.PropWarp: _path = aerp.PropWarpLoadPath(_name) + Suffixes; break;
                case EInfoType.GValue: _path = aerp.GValueLoadPath(_name) + Suffixes; break;
                case EInfoType.Equation: _path = aerp.EquationLoadPath(_name) + Suffixes; break;
                case EInfoType.Skill: _path = aerp.SkillLoadPath(_name) + Suffixes; break;

            }
            return _path;
        }

        public bool FullPathToResource(string _path, out string _runtimePath, string findName = "Resources")
        {
            string[] _pathArr = _path.Split('/');
            if (_pathArr.Length > 2)
            {
                bool _findResource = false;
                _runtimePath = string.Empty;
                for (int i = 1; i < _pathArr.Length - 1; i++)
                {
                    string _nowPathName = _pathArr[i];
                    if (_findResource)
                    {
                        _runtimePath += '/' + _nowPathName;
                    }
                    else
                    {
                        if (_nowPathName == findName)
                        {
                            i++;
                            _runtimePath = _pathArr[i];
                            _findResource = true;
                        }
                    }
                }

                if (_findResource)
                {
                    _runtimePath += '/' + _pathArr[^1].Split('.')[0];
                    return true;
                }
            }

            _runtimePath = string.Empty;
            return false;
        }
    }
}
